package com.crew.model;
// default package
// Generated Aug 19, 2015 4:51:16 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CrewlinkSuggestion generated by hbm2java
 */
@Entity
@Table(name = "crewlink_suggestion", catalog = "crewdb")
public class CrewlinkSuggestion implements java.io.Serializable {

	private Long id;
	private Long firstId;
	private Long secondId;
	private Integer difference;
	private String hqRest;

	public CrewlinkSuggestion() {
	}

	public CrewlinkSuggestion(Long firstId, Long secondId, Integer difference,
			String hqRest) {
		this.firstId = firstId;
		this.secondId = secondId;
		this.difference = difference;
		this.hqRest = hqRest;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "first_id")
	public Long getFirstId() {
		return this.firstId;
	}

	public void setFirstId(Long firstId) {
		this.firstId = firstId;
	}

	@Column(name = "second_id")
	public Long getSecondId() {
		return this.secondId;
	}

	public void setSecondId(Long secondId) {
		this.secondId = secondId;
	}

	@Column(name = "difference")
	public Integer getDifference() {
		return this.difference;
	}

	public void setDifference(Integer difference) {
		this.difference = difference;
	}

	@Column(name = "hq_rest", length = 6)
	public String getHqRest() {
		return this.hqRest;
	}

	public void setHqRest(String hqRest) {
		this.hqRest = hqRest;
	}

}
