package com.crew.model;
// default package
// Generated Sep 15, 2015 10:36:22 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * CrewLink generated by hbm2java
 */
public class CrewLink implements java.io.Serializable {

	private Long id;
	private Customer customer;
	private String trainNo;
	private String fromStation;
	private String toStation;
	private Date departure;
	private Date arrivalTime;
	private String outStationRest;
	private String headQuarterRest;
	private Integer periodicRest;
	private Integer noOfDays;
	private Date signoff;
	private Long transactionNoCrewLink;
	private String availability;
	private Boolean periodicRestAdded;
	private String crewBase;
	private String crewType;
	private String linkName;
	private String sequenceId;
	private Long distance;
	private String workingHour;
	private Long drivingSectionId;

	public CrewLink() {
	}

	public CrewLink(Customer customer, String trainNo, String fromStation,
			String toStation, Date departure, Date arrivalTime,
			String outStationRest, String headQuarterRest,
			Integer periodicRest, Integer noOfDays, Date signoff,
			Long transactionNoCrewLink, String availability,
			Boolean periodicRestAdded, String crewBase, String crewType,
			String linkName, String sequenceId, Long distance,
			String workingHour, Long drivingSectionId) {
		this.customer = customer;
		this.trainNo = trainNo;
		this.fromStation = fromStation;
		this.toStation = toStation;
		this.departure = departure;
		this.arrivalTime = arrivalTime;
		this.outStationRest = outStationRest;
		this.headQuarterRest = headQuarterRest;
		this.periodicRest = periodicRest;
		this.noOfDays = noOfDays;
		this.signoff = signoff;
		this.transactionNoCrewLink = transactionNoCrewLink;
		this.availability = availability;
		this.periodicRestAdded = periodicRestAdded;
		this.crewBase = crewBase;
		this.crewType = crewType;
		this.linkName = linkName;
		this.sequenceId = sequenceId;
		this.distance = distance;
		this.workingHour = workingHour;
		this.drivingSectionId = drivingSectionId;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public String getTrainNo() {
		return this.trainNo;
	}

	public void setTrainNo(String trainNo) {
		this.trainNo = trainNo;
	}

	public String getFromStation() {
		return this.fromStation;
	}

	public void setFromStation(String fromStation) {
		this.fromStation = fromStation;
	}

	public String getToStation() {
		return this.toStation;
	}

	public void setToStation(String toStation) {
		this.toStation = toStation;
	}

	public Date getDeparture() {
		return this.departure;
	}

	public void setDeparture(Date departure) {
		this.departure = departure;
	}

	public Date getArrivalTime() {
		return this.arrivalTime;
	}

	public void setArrivalTime(Date arrivalTime) {
		this.arrivalTime = arrivalTime;
	}

	public String getOutStationRest() {
		return this.outStationRest;
	}

	public void setOutStationRest(String outStationRest) {
		this.outStationRest = outStationRest;
	}

	public String getHeadQuarterRest() {
		return this.headQuarterRest;
	}

	public void setHeadQuarterRest(String headQuarterRest) {
		this.headQuarterRest = headQuarterRest;
	}

	public Integer getPeriodicRest() {
		return this.periodicRest;
	}

	public void setPeriodicRest(Integer periodicRest) {
		this.periodicRest = periodicRest;
	}

	public Integer getNoOfDays() {
		return this.noOfDays;
	}

	public void setNoOfDays(Integer noOfDays) {
		this.noOfDays = noOfDays;
	}

	public Date getSignoff() {
		return this.signoff;
	}

	public void setSignoff(Date signoff) {
		this.signoff = signoff;
	}

	public Long getTransactionNoCrewLink() {
		return this.transactionNoCrewLink;
	}

	public void setTransactionNoCrewLink(Long transactionNoCrewLink) {
		this.transactionNoCrewLink = transactionNoCrewLink;
	}

	public String getAvailability() {
		return this.availability;
	}

	public void setAvailability(String availability) {
		this.availability = availability;
	}

	public Boolean getPeriodicRestAdded() {
		return this.periodicRestAdded;
	}

	public void setPeriodicRestAdded(Boolean periodicRestAdded) {
		this.periodicRestAdded = periodicRestAdded;
	}

	public String getCrewBase() {
		return this.crewBase;
	}

	public void setCrewBase(String crewBase) {
		this.crewBase = crewBase;
	}

	public String getCrewType() {
		return this.crewType;
	}

	public void setCrewType(String crewType) {
		this.crewType = crewType;
	}

	public String getLinkName() {
		return this.linkName;
	}

	public void setLinkName(String linkName) {
		this.linkName = linkName;
	}

	public String getSequenceId() {
		return this.sequenceId;
	}

	public void setSequenceId(String sequenceId) {
		this.sequenceId = sequenceId;
	}

	public Long getDistance() {
		return this.distance;
	}

	public void setDistance(Long distance) {
		this.distance = distance;
	}

	public String getWorkingHour() {
		return this.workingHour;
	}

	public void setWorkingHour(String workingHour) {
		this.workingHour = workingHour;
	}

	public Long getDrivingSectionId() {
		return this.drivingSectionId;
	}

	public void setDrivingSectionId(Long drivingSectionId) {
		this.drivingSectionId = drivingSectionId;
	}

}
