package com.crew.model;
// default package
// Generated Aug 1, 2015 12:17:14 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CrewChangeDrivingsection generated by hbm2java
 */
@Entity
@Table(name = "crew_change_drivingsection", catalog = "crewdb")
public class CrewChangeDrivingsection implements java.io.Serializable {

	private Long id;
	private Customer customer;
	private String trainNo;
	private String fromStation;
	private String toStation;
	private String crewBase;
	private String crewType;
	private Long kilometer;
	private String hour;
	private Date departure;
	private Date arrival;
	private Boolean status;
	private String sequenceId;
	private Long transactionNoDsToDd;
	private String transactionId;
	private Long crewLinkSequence;
	private Long roundTripSequenceNo;
	private Boolean periodicRest;

	public CrewChangeDrivingsection() {
	}

	public CrewChangeDrivingsection(Customer customer, String trainNo,
			String fromStation, String toStation, String crewBase,
			String crewType, Long kilometer, String hour, Date departure,
			Date arrival, Boolean status, String sequenceId,
			Long transactionNoDsToDd, String transactionId,
			Long crewLinkSequence, Long roundTripSequenceNo,
			Boolean periodicRest) {
		this.customer = customer;
		this.trainNo = trainNo;
		this.fromStation = fromStation;
		this.toStation = toStation;
		this.crewBase = crewBase;
		this.crewType = crewType;
		this.kilometer = kilometer;
		this.hour = hour;
		this.departure = departure;
		this.arrival = arrival;
		this.status = status;
		this.sequenceId = sequenceId;
		this.transactionNoDsToDd = transactionNoDsToDd;
		this.transactionId = transactionId;
		this.crewLinkSequence = crewLinkSequence;
		this.roundTripSequenceNo = roundTripSequenceNo;
		this.periodicRest = periodicRest;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Cutomer_table_fk")
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@Column(name = "train_no", length = 10)
	public String getTrainNo() {
		return this.trainNo;
	}

	public void setTrainNo(String trainNo) {
		this.trainNo = trainNo;
	}

	@Column(name = "from_Station", length = 10)
	public String getFromStation() {
		return this.fromStation;
	}

	public void setFromStation(String fromStation) {
		this.fromStation = fromStation;
	}

	@Column(name = "To_station", length = 10)
	public String getToStation() {
		return this.toStation;
	}

	public void setToStation(String toStation) {
		this.toStation = toStation;
	}

	@Column(name = "Crew_Base", length = 10)
	public String getCrewBase() {
		return this.crewBase;
	}

	public void setCrewBase(String crewBase) {
		this.crewBase = crewBase;
	}

	@Column(name = "CrewType", length = 10)
	public String getCrewType() {
		return this.crewType;
	}

	public void setCrewType(String crewType) {
		this.crewType = crewType;
	}

	@Column(name = "kilometer")
	public Long getKilometer() {
		return this.kilometer;
	}

	public void setKilometer(Long kilometer) {
		this.kilometer = kilometer;
	}

	@Column(name = "hour", length = 10)
	public String getHour() {
		return this.hour;
	}

	public void setHour(String hour) {
		this.hour = hour;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "departure", length = 0)
	public Date getDeparture() {
		return this.departure;
	}

	public void setDeparture(Date departure) {
		this.departure = departure;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "arrival", length = 0)
	public Date getArrival() {
		return this.arrival;
	}

	public void setArrival(Date arrival) {
		this.arrival = arrival;
	}

	@Column(name = "status")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@Column(name = "sequence_id", length = 20)
	public String getSequenceId() {
		return this.sequenceId;
	}

	public void setSequenceId(String sequenceId) {
		this.sequenceId = sequenceId;
	}

	@Column(name = "transaction_No_DS_TO_DD")
	public Long getTransactionNoDsToDd() {
		return this.transactionNoDsToDd;
	}

	public void setTransactionNoDsToDd(Long transactionNoDsToDd) {
		this.transactionNoDsToDd = transactionNoDsToDd;
	}

	@Column(name = "transaction_id", length = 15)
	public String getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(String transactionId) {
		this.transactionId = transactionId;
	}

	@Column(name = "crew_link_sequence")
	public Long getCrewLinkSequence() {
		return this.crewLinkSequence;
	}

	public void setCrewLinkSequence(Long crewLinkSequence) {
		this.crewLinkSequence = crewLinkSequence;
	}

	@Column(name = "roundTrip_SequenceNo")
	public Long getRoundTripSequenceNo() {
		return this.roundTripSequenceNo;
	}

	public void setRoundTripSequenceNo(Long roundTripSequenceNo) {
		this.roundTripSequenceNo = roundTripSequenceNo;
	}

	@Column(name = "periodic_rest")
	public Boolean getPeriodicRest() {
		return this.periodicRest;
	}

	public void setPeriodicRest(Boolean periodicRest) {
		this.periodicRest = periodicRest;
	}

}
