package com.crew.model;
// default package
// Generated Apr 28, 2015 3:26:24 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CrewOutstation generated by hbm2java
 */
@Entity
@Table(name = "crew_outstation", catalog = "crewlinkssystem")
public class CrewOutstation implements java.io.Serializable {

	private Long id;
	private String stationCode;
	private Integer noOfRunningRoomBeds;
	private Integer timeGivenforSignOn;
	private Integer timeGivenforSignOff;

	public CrewOutstation() {
	}

	public CrewOutstation(String stationCode, Integer noOfRunningRoomBeds,
			Integer timeGivenforSignOn, Integer timeGivenforSignOff) {
		this.stationCode = stationCode;
		this.noOfRunningRoomBeds = noOfRunningRoomBeds;
		this.timeGivenforSignOn = timeGivenforSignOn;
		this.timeGivenforSignOff = timeGivenforSignOff;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "Station_Code", length = 7)
	public String getStationCode() {
		return this.stationCode;
	}

	public void setStationCode(String stationCode) {
		this.stationCode = stationCode;
	}

	@Column(name = "No_Of_RunningRoom_Beds")
	public Integer getNoOfRunningRoomBeds() {
		return this.noOfRunningRoomBeds;
	}

	public void setNoOfRunningRoomBeds(Integer noOfRunningRoomBeds) {
		this.noOfRunningRoomBeds = noOfRunningRoomBeds;
	}

	@Column(name = "TimeGivenforSignOn")
	public Integer getTimeGivenforSignOn() {
		return this.timeGivenforSignOn;
	}

	public void setTimeGivenforSignOn(Integer timeGivenforSignOn) {
		this.timeGivenforSignOn = timeGivenforSignOn;
	}

	@Column(name = "TimeGivenforSignOff")
	public Integer getTimeGivenforSignOff() {
		return this.timeGivenforSignOff;
	}

	public void setTimeGivenforSignOff(Integer timeGivenforSignOff) {
		this.timeGivenforSignOff = timeGivenforSignOff;
	}

}
