package com.crew.model;
// default package
// Generated Jul 27, 2015 2:07:48 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * DrivingDutyOfPilotDrivingSection generated by hbm2java
 */
@Entity
@Table(name = "driving_duty_of_pilot_driving_section", catalog = "crewdb", uniqueConstraints = @UniqueConstraint(columnNames = "driver_id"))
public class DrivingDutyOfPilotDrivingSection implements java.io.Serializable {

	private Long id;
	private Customer customer;
	private String trainNo;
	private String fromStation;
	private String toStation;
	private Date departure;
	private Date arrival;
	private Long km;
	private Date signonTime;
	private Date signoffTime;
	private Long dutyHours;
	private String availability;
	private String driverId;
	private String totalDutyHours;
	private String deletedId1;
	private String deletedId2;
	private String crewBase;
	private String crewType;
	private Long transactionNoDsToDd;
	private Long transactionNoDdToRt;
	private Long serialNoRt;
	private Boolean status;
	private String hqRest;
	private String osRest;
	private Long sequenceId;
	private Long pilotSequenceId;

	public DrivingDutyOfPilotDrivingSection() {
	}

	public DrivingDutyOfPilotDrivingSection(Customer customer, String trainNo,
			String fromStation, String toStation, Date departure, Date arrival,
			Long km, Date signonTime, Date signoffTime, Long dutyHours,
			String availability, String driverId, String totalDutyHours,
			String deletedId1, String deletedId2, String crewBase,
			String crewType, Long transactionNoDsToDd,
			Long transactionNoDdToRt, Long serialNoRt, Boolean status,
			String hqRest, String osRest, Long sequenceId, Long pilotSequenceId) {
		this.customer = customer;
		this.trainNo = trainNo;
		this.fromStation = fromStation;
		this.toStation = toStation;
		this.departure = departure;
		this.arrival = arrival;
		this.km = km;
		this.signonTime = signonTime;
		this.signoffTime = signoffTime;
		this.dutyHours = dutyHours;
		this.availability = availability;
		this.driverId = driverId;
		this.totalDutyHours = totalDutyHours;
		this.deletedId1 = deletedId1;
		this.deletedId2 = deletedId2;
		this.crewBase = crewBase;
		this.crewType = crewType;
		this.transactionNoDsToDd = transactionNoDsToDd;
		this.transactionNoDdToRt = transactionNoDdToRt;
		this.serialNoRt = serialNoRt;
		this.status = status;
		this.hqRest = hqRest;
		this.osRest = osRest;
		this.sequenceId = sequenceId;
		this.pilotSequenceId = pilotSequenceId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_table_fk")
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@Column(name = "train_no", length = 400)
	public String getTrainNo() {
		return this.trainNo;
	}

	public void setTrainNo(String trainNo) {
		this.trainNo = trainNo;
	}

	@Column(name = "from_station", length = 10)
	public String getFromStation() {
		return this.fromStation;
	}

	public void setFromStation(String fromStation) {
		this.fromStation = fromStation;
	}

	@Column(name = "to_station", length = 10)
	public String getToStation() {
		return this.toStation;
	}

	public void setToStation(String toStation) {
		this.toStation = toStation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "departure", length = 0)
	public Date getDeparture() {
		return this.departure;
	}

	public void setDeparture(Date departure) {
		this.departure = departure;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "arrival", length = 0)
	public Date getArrival() {
		return this.arrival;
	}

	public void setArrival(Date arrival) {
		this.arrival = arrival;
	}

	@Column(name = "km")
	public Long getKm() {
		return this.km;
	}

	public void setKm(Long km) {
		this.km = km;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "signon_time", length = 0)
	public Date getSignonTime() {
		return this.signonTime;
	}

	public void setSignonTime(Date signonTime) {
		this.signonTime = signonTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "signoff_time", length = 0)
	public Date getSignoffTime() {
		return this.signoffTime;
	}

	public void setSignoffTime(Date signoffTime) {
		this.signoffTime = signoffTime;
	}

	@Column(name = "duty_hours")
	public Long getDutyHours() {
		return this.dutyHours;
	}

	public void setDutyHours(Long dutyHours) {
		this.dutyHours = dutyHours;
	}

	@Column(name = "availability", length = 20)
	public String getAvailability() {
		return this.availability;
	}

	public void setAvailability(String availability) {
		this.availability = availability;
	}

	@Column(name = "driver_id", unique = true, length = 4)
	public String getDriverId() {
		return this.driverId;
	}

	public void setDriverId(String driverId) {
		this.driverId = driverId;
	}

	@Column(name = "total_duty_hours", length = 10)
	public String getTotalDutyHours() {
		return this.totalDutyHours;
	}

	public void setTotalDutyHours(String totalDutyHours) {
		this.totalDutyHours = totalDutyHours;
	}

	@Column(name = "deleted_id1", length = 10)
	public String getDeletedId1() {
		return this.deletedId1;
	}

	public void setDeletedId1(String deletedId1) {
		this.deletedId1 = deletedId1;
	}

	@Column(name = "deleted_id2", length = 10)
	public String getDeletedId2() {
		return this.deletedId2;
	}

	public void setDeletedId2(String deletedId2) {
		this.deletedId2 = deletedId2;
	}

	@Column(name = "crew_base", length = 10)
	public String getCrewBase() {
		return this.crewBase;
	}

	public void setCrewBase(String crewBase) {
		this.crewBase = crewBase;
	}

	@Column(name = "crew_type", length = 10)
	public String getCrewType() {
		return this.crewType;
	}

	public void setCrewType(String crewType) {
		this.crewType = crewType;
	}

	@Column(name = "transaction_No_DS_TO_DD")
	public Long getTransactionNoDsToDd() {
		return this.transactionNoDsToDd;
	}

	public void setTransactionNoDsToDd(Long transactionNoDsToDd) {
		this.transactionNoDsToDd = transactionNoDsToDd;
	}

	@Column(name = "transaction_No_DD_TO_RT")
	public Long getTransactionNoDdToRt() {
		return this.transactionNoDdToRt;
	}

	public void setTransactionNoDdToRt(Long transactionNoDdToRt) {
		this.transactionNoDdToRt = transactionNoDdToRt;
	}

	@Column(name = "Serial_No_RT")
	public Long getSerialNoRt() {
		return this.serialNoRt;
	}

	public void setSerialNoRt(Long serialNoRt) {
		this.serialNoRt = serialNoRt;
	}

	@Column(name = "status")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@Column(name = "hq_rest", length = 20)
	public String getHqRest() {
		return this.hqRest;
	}

	public void setHqRest(String hqRest) {
		this.hqRest = hqRest;
	}

	@Column(name = "os_rest", length = 20)
	public String getOsRest() {
		return this.osRest;
	}

	public void setOsRest(String osRest) {
		this.osRest = osRest;
	}

	@Column(name = "sequence_id")
	public Long getSequenceId() {
		return this.sequenceId;
	}

	public void setSequenceId(Long sequenceId) {
		this.sequenceId = sequenceId;
	}

	@Column(name = "Pilot_sequence_id")
	public Long getPilotSequenceId() {
		return this.pilotSequenceId;
	}

	public void setPilotSequenceId(Long pilotSequenceId) {
		this.pilotSequenceId = pilotSequenceId;
	}

}
