package com.crew.model;
// default package
// Generated May 5, 2015 11:07:20 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DrivingDuty generated by hbm2java
 */
@Entity
@Table(name = "driving_duty", catalog = "crewlinkssystem")
public class DrivingDuty implements java.io.Serializable {

	private Long id;
	private String trainNo;
	private String fromStation;
	private String toStation;
	private Date departureTime;
	private Date arrivalTime;
	private Date signOnTime;
	private Date signOffTime;
	private Date availabilityTime;
	private Long distance;

	public DrivingDuty() {
	}

	public DrivingDuty(String trainNo, String fromStation, String toStation,
			Date departureTime, Date arrivalTime, Date signOnTime,
			Date signOffTime, Date availabilityTime, Long distance) {
		this.trainNo = trainNo;
		this.fromStation = fromStation;
		this.toStation = toStation;
		this.departureTime = departureTime;
		this.arrivalTime = arrivalTime;
		this.signOnTime = signOnTime;
		this.signOffTime = signOffTime;
		this.availabilityTime = availabilityTime;
		this.distance = distance;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "Train No", length = 30)
	public String getTrainNo() {
		return this.trainNo;
	}

	public void setTrainNo(String trainNo) {
		this.trainNo = trainNo;
	}

	@Column(name = "From_Station", length = 5)
	public String getFromStation() {
		return this.fromStation;
	}

	public void setFromStation(String fromStation) {
		this.fromStation = fromStation;
	}

	@Column(name = "To_Station", length = 5)
	public String getToStation() {
		return this.toStation;
	}

	public void setToStation(String toStation) {
		this.toStation = toStation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Departure_Time", length = 0)
	public Date getDepartureTime() {
		return this.departureTime;
	}

	public void setDepartureTime(Date departureTime) {
		this.departureTime = departureTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Arrival_Time", length = 0)
	public Date getArrivalTime() {
		return this.arrivalTime;
	}

	public void setArrivalTime(Date arrivalTime) {
		this.arrivalTime = arrivalTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SignOn_Time", length = 0)
	public Date getSignOnTime() {
		return this.signOnTime;
	}

	public void setSignOnTime(Date signOnTime) {
		this.signOnTime = signOnTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SignOff_Time", length = 0)
	public Date getSignOffTime() {
		return this.signOffTime;
	}

	public void setSignOffTime(Date signOffTime) {
		this.signOffTime = signOffTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Availability_Time", length = 0)
	public Date getAvailabilityTime() {
		return this.availabilityTime;
	}

	public void setAvailabilityTime(Date availabilityTime) {
		this.availabilityTime = availabilityTime;
	}

	@Column(name = "distance")
	public Long getDistance() {
		return this.distance;
	}

	public void setDistance(Long distance) {
		this.distance = distance;
	}

}
