package com.crew.model;
// default package
// Generated May 19, 2015 12:49:19 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Finaltable generated by hbm2java
 */
@Entity
@Table(name = "finaltable", catalog = "crewdb", uniqueConstraints = @UniqueConstraint(columnNames = {
		"trainno1", "trainno2" }))
public class Finaltable implements java.io.Serializable {

	private Long slno;
	private String trainno1;
	private String trainno2;
	private Long differecnce;
	private String startingStation;
	private String destStation;

	public Finaltable() {
	}

	public Finaltable(String trainno1, String trainno2, Long differecnce,
			String startingStation, String destStation) {
		this.trainno1 = trainno1;
		this.trainno2 = trainno2;
		this.differecnce = differecnce;
		this.startingStation = startingStation;
		this.destStation = destStation;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "slno", unique = true, nullable = false)
	public Long getSlno() {
		return this.slno;
	}

	public void setSlno(Long slno) {
		this.slno = slno;
	}

	@Column(name = "trainno1", length = 10)
	public String getTrainno1() {
		return this.trainno1;
	}

	public void setTrainno1(String trainno1) {
		this.trainno1 = trainno1;
	}

	@Column(name = "trainno2", length = 10)
	public String getTrainno2() {
		return this.trainno2;
	}

	public void setTrainno2(String trainno2) {
		this.trainno2 = trainno2;
	}

	@Column(name = "differecnce")
	public Long getDifferecnce() {
		return this.differecnce;
	}

	public void setDifferecnce(Long differecnce) {
		this.differecnce = differecnce;
	}

	@Column(name = "starting_station", length = 10)
	public String getStartingStation() {
		return this.startingStation;
	}

	public void setStartingStation(String startingStation) {
		this.startingStation = startingStation;
	}

	@Column(name = "dest_station", length = 10)
	public String getDestStation() {
		return this.destStation;
	}

	public void setDestStation(String destStation) {
		this.destStation = destStation;
	}

}
