package com.crew.model;
// default package
// Generated Sep 3, 2015 1:41:08 PM by Hibernate Tools 3.4.0.CR1

/**
 * FinalRoundtripSuggestion generated by hbm2java
 */
public class FinalRoundtripSuggestion implements java.io.Serializable {

	private Long id;
	private String trainno1;
	private String trainno2;

	public FinalRoundtripSuggestion() {
	}

	public FinalRoundtripSuggestion(String trainno1, String trainno2) {
		this.trainno1 = trainno1;
		this.trainno2 = trainno2;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getTrainno1() {
		return this.trainno1;
	}

	public void setTrainno1(String trainno1) {
		this.trainno1 = trainno1;
	}

	public String getTrainno2() {
		return this.trainno2;
	}

	public void setTrainno2(String trainno2) {
		this.trainno2 = trainno2;
	}

}
