package com.crew.model;
// default package
// Generated Aug 15, 2015 7:45:16 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * HqOsRest generated by hbm2java
 */
@Entity
@Table(name = "hq_os_rest", catalog = "crewdb")
public class HqOsRest implements java.io.Serializable {

	private Long id;
	private Integer hqRest;
	private Integer osRest;

	public HqOsRest() {
	}

	public HqOsRest(Integer hqRest, Integer osRest) {
		this.hqRest = hqRest;
		this.osRest = osRest;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "hq_rest")
	public Integer getHqRest() {
		return this.hqRest;
	}

	public void setHqRest(Integer hqRest) {
		this.hqRest = hqRest;
	}

	@Column(name = "os_rest")
	public Integer getOsRest() {
		return this.osRest;
	}

	public void setOsRest(Integer osRest) {
		this.osRest = osRest;
	}

}
