package com.crew.model;
// default package
// Generated Apr 28, 2015 3:26:24 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * InsSecToDuty generated by hbm2java
 */
@Entity
@Table(name = "ins_sec_to_duty", catalog = "crewlinkssystem")
public class InsSecToDuty implements java.io.Serializable {

	private Long id;

	public InsSecToDuty() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

}
