package com.crew.model;
// default package
// Generated May 6, 2015 12:59:57 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Onedrivingsection generated by hbm2java
 */
@Entity
@Table(name = "onedrivingsection", catalog = "crewlinkssystem")
public class Onedrivingsection implements java.io.Serializable {

	private Long id;
	private String trainNo;
	private String fromStation;
	private String toStation;
	private Date departureTime;
	private Date arrivalTime;
	private Date signOn;
	private Date signOff;
	private Integer availabilityTime;
	private Long distance;
	private Date dutyHour;

	public Onedrivingsection() {
	}

	public Onedrivingsection(String trainNo, String fromStation,
			String toStation, Date departureTime, Date arrivalTime,
			Date signOn, Date signOff, Integer availabilityTime, Long distance,
			Date dutyHour) {
		this.trainNo = trainNo;
		this.fromStation = fromStation;
		this.toStation = toStation;
		this.departureTime = departureTime;
		this.arrivalTime = arrivalTime;
		this.signOn = signOn;
		this.signOff = signOff;
		this.availabilityTime = availabilityTime;
		this.distance = distance;
		this.dutyHour = dutyHour;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "Train_No", length = 30)
	public String getTrainNo() {
		return this.trainNo;
	}

	public void setTrainNo(String trainNo) {
		this.trainNo = trainNo;
	}

	@Column(name = "From_Station", length = 5)
	public String getFromStation() {
		return this.fromStation;
	}

	public void setFromStation(String fromStation) {
		this.fromStation = fromStation;
	}

	@Column(name = "To_Station", length = 5)
	public String getToStation() {
		return this.toStation;
	}

	public void setToStation(String toStation) {
		this.toStation = toStation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "departure_Time", length = 0)
	public Date getDepartureTime() {
		return this.departureTime;
	}

	public void setDepartureTime(Date departureTime) {
		this.departureTime = departureTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "arrival_Time", length = 0)
	public Date getArrivalTime() {
		return this.arrivalTime;
	}

	public void setArrivalTime(Date arrivalTime) {
		this.arrivalTime = arrivalTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "sign_On", length = 0)
	public Date getSignOn() {
		return this.signOn;
	}

	public void setSignOn(Date signOn) {
		this.signOn = signOn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "sign_Off", length = 0)
	public Date getSignOff() {
		return this.signOff;
	}

	public void setSignOff(Date signOff) {
		this.signOff = signOff;
	}

	@Column(name = "availability_Time")
	public Integer getAvailabilityTime() {
		return this.availabilityTime;
	}

	public void setAvailabilityTime(Integer availabilityTime) {
		this.availabilityTime = availabilityTime;
	}

	@Column(name = "distance")
	public Long getDistance() {
		return this.distance;
	}

	public void setDistance(Long distance) {
		this.distance = distance;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "duty_hour", length = 0)
	public Date getDutyHour() {
		return this.dutyHour;
	}

	public void setDutyHour(Date dutyHour) {
		this.dutyHour = dutyHour;
	}

}
