package com.crew.model;
// default package
// Generated May 18, 2015 5:20:04 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Optimizedresult generated by hbm2java
 */
@Entity
@Table(name = "optimizedresult", catalog = "crewdb")
public class Optimizedresult implements java.io.Serializable {

	private Long slno;
	private String from;
	private String to;
	private Date available;
	private Date departure;
	private String driverid1;
	private String driverid2;

	public Optimizedresult() {
	}

	public Optimizedresult(String from, String to, Date available,
			Date departure, String driverid1, String driverid2) {
		this.from = from;
		this.to = to;
		this.available = available;
		this.departure = departure;
		this.driverid1 = driverid1;
		this.driverid2 = driverid2;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "slno", unique = true, nullable = false)
	public Long getSlno() {
		return this.slno;
	}

	public void setSlno(Long slno) {
		this.slno = slno;
	}

	@Column(name = "from", length = 5)
	public String getFrom() {
		return this.from;
	}

	public void setFrom(String from) {
		this.from = from;
	}

	@Column(name = "to", length = 5)
	public String getTo() {
		return this.to;
	}

	public void setTo(String to) {
		this.to = to;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "available", length = 0)
	public Date getAvailable() {
		return this.available;
	}

	public void setAvailable(Date available) {
		this.available = available;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "departure", length = 0)
	public Date getDeparture() {
		return this.departure;
	}

	public void setDeparture(Date departure) {
		this.departure = departure;
	}

	@Column(name = "driverid1", length = 5)
	public String getDriverid1() {
		return this.driverid1;
	}

	public void setDriverid1(String driverid1) {
		this.driverid1 = driverid1;
	}

	@Column(name = "driverid2", length = 5)
	public String getDriverid2() {
		return this.driverid2;
	}

	public void setDriverid2(String driverid2) {
		this.driverid2 = driverid2;
	}

}
