package com.crew.model;
// default package
// Generated Sep 3, 2015 10:06:57 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * RoundtripTemp generated by hbm2java
 */
public class RoundtripTemp implements java.io.Serializable {

	private Long id;
	private String fromStation;
	private String toStation;
	private String trainNo;
	private Date departure;
	private Date arrival;
	private Date signon;
	private Date signonff;
	private String availability;

	public RoundtripTemp() {
	}

	public RoundtripTemp(String fromStation, String toStation, String trainNo,
			Date departure, Date arrival, Date signon, Date signonff,
			String availability) {
		this.fromStation = fromStation;
		this.toStation = toStation;
		this.trainNo = trainNo;
		this.departure = departure;
		this.arrival = arrival;
		this.signon = signon;
		this.signonff = signonff;
		this.availability = availability;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getFromStation() {
		return this.fromStation;
	}

	public void setFromStation(String fromStation) {
		this.fromStation = fromStation;
	}

	public String getToStation() {
		return this.toStation;
	}

	public void setToStation(String toStation) {
		this.toStation = toStation;
	}

	public String getTrainNo() {
		return this.trainNo;
	}

	public void setTrainNo(String trainNo) {
		this.trainNo = trainNo;
	}

	public Date getDeparture() {
		return this.departure;
	}

	public void setDeparture(Date departure) {
		this.departure = departure;
	}

	public Date getArrival() {
		return this.arrival;
	}

	public void setArrival(Date arrival) {
		this.arrival = arrival;
	}

	public Date getSignon() {
		return this.signon;
	}

	public void setSignon(Date signon) {
		this.signon = signon;
	}

	public Date getSignonff() {
		return this.signonff;
	}

	public void setSignonff(Date signonff) {
		this.signonff = signonff;
	}

	public String getAvailability() {
		return this.availability;
	}

	public void setAvailability(String availability) {
		this.availability = availability;
	}

}
