package com.crew.model;
// default package
// Generated Aug 15, 2015 11:54:28 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Test2 generated by hbm2java
 */
@Entity
@Table(name = "test2", catalog = "crewdb")
public class Test2 implements java.io.Serializable {

	private Long id;
	private String trainNo;
	private String fromStation;
	private String toStation;
	private Date departure;
	private Date arrival;
	private Integer distance;

	public Test2() {
	}

	public Test2(String trainNo, String fromStation, String toStation,
			Date departure, Date arrival, Integer distance) {
		this.trainNo = trainNo;
		this.fromStation = fromStation;
		this.toStation = toStation;
		this.departure = departure;
		this.arrival = arrival;
		this.distance = distance;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "Train_No", length = 10)
	public String getTrainNo() {
		return this.trainNo;
	}

	public void setTrainNo(String trainNo) {
		this.trainNo = trainNo;
	}

	@Column(name = "From_Station", length = 10)
	public String getFromStation() {
		return this.fromStation;
	}

	public void setFromStation(String fromStation) {
		this.fromStation = fromStation;
	}

	@Column(name = "To_Station", length = 10)
	public String getToStation() {
		return this.toStation;
	}

	public void setToStation(String toStation) {
		this.toStation = toStation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Departure", length = 0)
	public Date getDeparture() {
		return this.departure;
	}

	public void setDeparture(Date departure) {
		this.departure = departure;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Arrival", length = 0)
	public Date getArrival() {
		return this.arrival;
	}

	public void setArrival(Date arrival) {
		this.arrival = arrival;
	}

	@Column(name = "Distance")
	public Integer getDistance() {
		return this.distance;
	}

	public void setDistance(Integer distance) {
		this.distance = distance;
	}

}
