package com.crew.model;
// default package
// Generated Aug 15, 2015 10:47:28 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Test generated by hbm2java
 */
@Entity
@Table(name = "test", catalog = "crewdb")
public class Test implements java.io.Serializable {

	private Long id;
	private String trainNo;
	private String fromStation;
	private String toStation;
	private Date departure;
	private Date arrival;
	private Integer distance;
	private Byte crewChange;
	private String locoChange;
	private Boolean hq;
	private Boolean os;
	private String crewBase;
	private String crewType;

	public Test() {
	}

	public Test(String trainNo, String fromStation, String toStation,
			Date departure, Date arrival, Integer distance, Byte crewChange,
			String locoChange, Boolean hq, Boolean os, String crewBase,
			String crewType) {
		this.trainNo = trainNo;
		this.fromStation = fromStation;
		this.toStation = toStation;
		this.departure = departure;
		this.arrival = arrival;
		this.distance = distance;
		this.crewChange = crewChange;
		this.locoChange = locoChange;
		this.hq = hq;
		this.os = os;
		this.crewBase = crewBase;
		this.crewType = crewType;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "Train_No", length = 10)
	public String getTrainNo() {
		return this.trainNo;
	}

	public void setTrainNo(String trainNo) {
		this.trainNo = trainNo;
	}

	@Column(name = "from_station", length = 8)
	public String getFromStation() {
		return this.fromStation;
	}

	public void setFromStation(String fromStation) {
		this.fromStation = fromStation;
	}

	@Column(name = "to_station", length = 10)
	public String getToStation() {
		return this.toStation;
	}

	public void setToStation(String toStation) {
		this.toStation = toStation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Departure", length = 0)
	public Date getDeparture() {
		return this.departure;
	}

	public void setDeparture(Date departure) {
		this.departure = departure;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Arrival", length = 0)
	public Date getArrival() {
		return this.arrival;
	}

	public void setArrival(Date arrival) {
		this.arrival = arrival;
	}

	@Column(name = "Distance")
	public Integer getDistance() {
		return this.distance;
	}

	public void setDistance(Integer distance) {
		this.distance = distance;
	}

	@Column(name = "crew_change")
	public Byte getCrewChange() {
		return this.crewChange;
	}

	public void setCrewChange(Byte crewChange) {
		this.crewChange = crewChange;
	}

	@Column(name = "loco_Change", length = 10)
	public String getLocoChange() {
		return this.locoChange;
	}

	public void setLocoChange(String locoChange) {
		this.locoChange = locoChange;
	}

	@Column(name = "HQ")
	public Boolean getHq() {
		return this.hq;
	}

	public void setHq(Boolean hq) {
		this.hq = hq;
	}

	@Column(name = "OS")
	public Boolean getOs() {
		return this.os;
	}

	public void setOs(Boolean os) {
		this.os = os;
	}

	@Column(name = "crew_base", length = 5)
	public String getCrewBase() {
		return this.crewBase;
	}

	public void setCrewBase(String crewBase) {
		this.crewBase = crewBase;
	}

	@Column(name = "crew_type", length = 5)
	public String getCrewType() {
		return this.crewType;
	}

	public void setCrewType(String crewType) {
		this.crewType = crewType;
	}

}
