package com.crew.model;
// default package
// Generated Jun 15, 2015 11:06:08 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TimeTableMaster generated by hbm2java
 */
@Entity
@Table(name = "time_table_master", catalog = "crewdb")
public class TimeTableMaster implements java.io.Serializable {

	private Long id;
	private String trainNo;
	private String stationCode;
	private Date arrival;
	private Date departure;
	private Integer distance;
	private Byte crewChange;
	private String locoChange;
	private Boolean hq;
	private Boolean os;

	public TimeTableMaster() {
	}

	public TimeTableMaster(String trainNo, String stationCode, Date arrival,
			Date departure, Integer distance, Byte crewChange,
			String locoChange, Boolean hq, Boolean os) {
		this.trainNo = trainNo;
		this.stationCode = stationCode;
		this.arrival = arrival;
		this.departure = departure;
		this.distance = distance;
		this.crewChange = crewChange;
		this.locoChange = locoChange;
		this.hq = hq;
		this.os = os;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "Train_No", length = 10)
	public String getTrainNo() {
		return this.trainNo;
	}

	public void setTrainNo(String trainNo) {
		this.trainNo = trainNo;
	}

	@Column(name = "Station_Code", length = 8)
	public String getStationCode() {
		return this.stationCode;
	}

	public void setStationCode(String stationCode) {
		this.stationCode = stationCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Arrival", length = 0)
	public Date getArrival() {
		return this.arrival;
	}

	public void setArrival(Date arrival) {
		this.arrival = arrival;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Departure", length = 0)
	public Date getDeparture() {
		return this.departure;
	}

	public void setDeparture(Date departure) {
		this.departure = departure;
	}

	@Column(name = "Distance")
	public Integer getDistance() {
		return this.distance;
	}

	public void setDistance(Integer distance) {
		this.distance = distance;
	}

	@Column(name = "crew_change")
	public Byte getCrewChange() {
		return this.crewChange;
	}

	public void setCrewChange(Byte crewChange) {
		this.crewChange = crewChange;
	}

	@Column(name = "loco_Change", length = 10)
	public String getLocoChange() {
		return this.locoChange;
	}

	public void setLocoChange(String locoChange) {
		this.locoChange = locoChange;
	}

	@Column(name = "HQ")
	public Boolean getHq() {
		return this.hq;
	}

	public void setHq(Boolean hq) {
		this.hq = hq;
	}

	@Column(name = "OS")
	public Boolean getOs() {
		return this.os;
	}

	public void setOs(Boolean os) {
		this.os = os;
	}

}
