package com.crew.model;
// default package
// Generated Jun 11, 2015 3:01:45 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TransactionIdDdRr generated by hbm2java
 */
@Entity
@Table(name = "transaction_id_dd_rr", catalog = "crewdb")
public class TransactionIdDdRr implements java.io.Serializable {

	private Long id;
	private Long transactionIdDdRr;

	public TransactionIdDdRr() {
	}

	public TransactionIdDdRr(Long transactionIdDdRr) {
		this.transactionIdDdRr = transactionIdDdRr;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "transaction_id_dd_rr")
	public Long getTransactionIdDdRr() {
		return this.transactionIdDdRr;
	}

	public void setTransactionIdDdRr(Long transactionIdDdRr) {
		this.transactionIdDdRr = transactionIdDdRr;
	}

}
