package com.crew.model;
// default package
// Generated Jun 20, 2015 11:21:32 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TransactionIdRrCl generated by hbm2java
 */
@Entity
@Table(name = "transaction_id_rr_cl", catalog = "crewdb")
public class TransactionIdRrCl implements java.io.Serializable {

	private Long slno;
	private Long transactionIdRrCl;

	public TransactionIdRrCl() {
	}

	public TransactionIdRrCl(Long transactionIdRrCl) {
		this.transactionIdRrCl = transactionIdRrCl;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "slno", unique = true, nullable = false)
	public Long getSlno() {
		return this.slno;
	}

	public void setSlno(Long slno) {
		this.slno = slno;
	}

	@Column(name = "transaction_id_rr_cl")
	public Long getTransactionIdRrCl() {
		return this.transactionIdRrCl;
	}

	public void setTransactionIdRrCl(Long transactionIdRrCl) {
		this.transactionIdRrCl = transactionIdRrCl;
	}

}
