package com.crew.model;
// default package
// Generated Jun 9, 2015 5:37:48 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TransactionIdGenerator generated by hbm2java
 */
@Entity
@Table(name = "transaction_id_generator", catalog = "crewdb")
public class TransactionIdGenerator implements java.io.Serializable {

	private Long id;
	private Long transactionId;

	public TransactionIdGenerator() {
	}

	public TransactionIdGenerator(Long transactionId) {
		this.transactionId = transactionId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "transaction_id")
	public Long getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(Long transactionId) {
		this.transactionId = transactionId;
	}

}
